# Generated by Django 4.1.7 on 2023-03-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_builder.node')),
            ],
        ),
    ]
