# Generated by Django 4.1.7 on 2023-03-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tree_builder.node'),
        ),
    ]
