# Generated by Django 4.1.7 on 2023-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="menu_name",
            field=models.CharField(default="first_menu", max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="option",
            field=models.CharField(
                default="DEFAULT_OPTION", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
