# Generated by Django 4.1.7 on 2023-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_builder", "0002_alter_node_menu_name_alter_node_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="slug",
            field=models.SlugField(),
        ),
    ]
