# Generated by Django 4.1.7 on 2023-03-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_builder', '0002_alter_node_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tree_builder.node'),
        ),
    ]
