# Generated by Django 4.1.7 on 2023-03-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_builder", "0003_alter_node_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="children",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tree_builder.node",
            ),
        ),
    ]
