# Generated by Django 4.1.7 on 2023-03-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_builder', '0004_alter_node_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='children',
            new_name='parent',
        ),
    ]
