# Generated by Django 4.1.7 on 2023-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_builder", "0005_rename_children_node_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="menu_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
