# Generated by Django 4.1.7 on 2023-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_builder', '0008_alter_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
