# Generated by Django 4.1.7 on 2023-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_builder", "0009_node_url_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="url_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
